### ISSUE TITLE
No color and many emojis are missing

### ISSUE THREAD

**Issue by Silent-Hunter** [fdw/rofimoji#13] opened 2019-06-29 17:38 UTC
There's no color, and a lot of emojis are missing. I'm using the Blobmoji fork of Noto Color Emojis font.

https://github.com/C1710/blobmoji

Unfortunately I can't take a screenshot because rofi grabs keyboard input. I can take a picture with my phone if you'd like, however.

**Comment by polyzen** [comment] 2019-06-29 17:49
> [`Alt-Shift-S` | Take a screenshot and store it in the Pictures directory.](https://github.com/davatorium/rofi#key-bindings)

**Comment by polyzen** [comment] 2019-06-29 17:52
Color emoji work fine here, btw, and there shouldn't be any emoji missing:
https://github.com/fdw/rofimoji/commit/b1307563a93aa23f64cea598792eb171b1e787b9

**Comment by fdw** [comment] 2019-06-29 19:21
To be honest, that sounds like a font issue to me. Could you please try another font, like [Noto Emoji](https://www.google.com/get/noto/)?

**Comment by Silent-Hunter** [comment] 2019-06-29 22:23
Okay, I edited the "~/.config/fontconfig/fonts.conf" file to make "Noto Color Emoji" the font that should be used. And the pictures are what's missing, it has the entries but it just shows the square with the unicode hexadecimal ID in it.
![rofi-2019-06-29-1520](https://user-images.githubusercontent.com/3732535/60390011-d1a1a080-9a81-11e9-807a-06ed8eb4ab5a.png)

**Comment by fdw** [comment] 2019-06-30 07:58
That definitely is a font issue.

If I remember correctly, these emojis are from the symbola font, which is monochrome and not that nice (IMO). What you can try:
- Just deinstall symbola (this is my current solution)
- https://askubuntu.com/questions/963840/how-do-i-configure-the-default-emoji-font-to-be-used-in-os-browser-its-curren (I think I did this before and it worked? At least, I still have the font config)
- https://www.reddit.com/r/archlinux/comments/3goivp/better_emoji_because_symbola_is_ugly/

**Comment by Silent-Hunter** [comment] 2019-06-30 14:45
Unfortunately I didn't have symbola installed, so it can't be that. I tried that font config from the askubuntu link there, and now it looks like this.

![rofi-2019-06-30-0731](https://user-images.githubusercontent.com/3732535/60398189-5e903c80-9b0a-11e9-98b8-2a81044adfb3.png)

The problem is, other fonts are bad now, geany looks like this.

![xscreenshot-Sun Jun 30 07:38:31 PDT 2019](https://user-images.githubusercontent.com/3732535/60398200-7ff12880-9b0a-11e9-81d9-4c088fbf53a0.png)

I tried changing the font config to reference "Noto Color Emoji" instead of "Noto Emoji" but that just made everything look like it did before. Same with "Blobmoji".

I just realized I never said what Linux I'm using. I'm using Debian 9. Also I don't know if it matters, but I had to use a custom kernel because otherwise everything on this PC displays sideways. Other than that it's stock Debian 9.

**Comment by fdw** [comment] 2019-06-30 15:16
Hm. Good news, this is definitely a font issue. Bad news, sorting this out isn't easy or straightforward. I could imagine that the font you're using (Noto Color Emoji?) contains glyphs for numbers, so it ends up looking like this. Maybe a different package or a different font could help.

Unfortunately, I'm on Manjaro now (and Ubuntu some time ago), so I don't know how to get the correct fonts for Debian. Sorry.

**Comment by Silent-Hunter** [comment] 2019-06-30 15:20
Well can you tell me the names of the fonts? I might be able to figure out what packages I need. Also, even with the messed up numbers, the emojis aren't in color in rofimoji. The odd thing is though, they work fine in Vivaldi browser. They're in color and everything.

**Comment by fdw** [comment] 2019-06-30 15:55
I'm using the `noto-fonts-emoji` font from Manjaro's repos. It shows in color in rofi (as you can see from the readme). I think I also used `emojione` for some time.

Maybe you have both the colored and monochrome emoji fonts installed?

**Comment by Silent-Hunter** [comment] 2019-07-01 01:21
I shouldn't have any emoji fonts installed except for Blobmoji. I do have the others but they aren't in my fontconfig. I do have the dejavu fontset installed, but uninstalling it doesn't change anything in rofimoji. The good news is I can still use rofimoji, it just doesn't look nice.

**Comment by fdw** [comment] 2019-07-01 06:24
You're right, it's not Symbola but Dejavu - at least some of the emojis in your screenshot are from that font ("slightly smiling face", for example). Now you should at least have a consistent monochrome font.

Could it be that the Blobmoji font contains both colored and monochrome variants, and rofi chooses the black/white one as it can't display the color encoding? I don't know whether that is true, but at least it sounds like a good hypothesis.

**Comment by Silent-Hunter** [comment] 2019-07-01 06:36
I thought that too possibly, but the Blobmoji developer tried rofimoji on their Fedora 28 installation and it worked fine. So I'm thinking it's something with my font configuration. I even tried forcing rofi to use blobmoji as its main font via fontconfig, and that didn't work either.
-------- Original Message --------

**Comment by fdw** [comment] 2019-07-01 08:41
Okay, just for completeness' sake, here's the relevant part from my fontconfig:
```
 <alias>
   <family>sans-serif</family>
   <prefer>
     <family>Liberation Sans</family>
     <family>Noto Color Emoji</family>
     <family>Noto Emoji</family>
   </prefer> 
 </alias>

 <alias>
   <family>serif</family>
   <prefer>
     <family>Liberation Serif</family>
     <family>Noto Color Emoji</family>
     <family>Noto Emoji</family>
   </prefer>
 </alias>

 <alias>
  <family>monospace</family>
  <prefer>
    <family>FiraMono For Nerd Font</family>
    <family>Noto Color Emoji</family>
    <family>Noto Emoji</family>
   </prefer>
 </alias>
```

Also, I still have dejavu installed, for some weird reason...

**Comment by Silent-Hunter** [comment] 2019-07-01 18:13
Okay, I tried your fontconfig, it still doesn't work unfortunately.

```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">

<fontconfig>
 <alias>
   <family>sans-serif</family>
   <prefer>
     <family>Liberation Sans</family>
     <family>Noto Color Emoji</family>
     <family>Noto Emoji</family>
   </prefer>
 </alias>

 <alias>
   <family>serif</family>
   <prefer>
     <family>Liberation Serif</family>
     <family>Noto Color Emoji</family>
     <family>Noto Emoji</family>
   </prefer>
 </alias>

 <alias>
  <family>monospace</family>
  <prefer>
    <family>Liberation Sans Mono</family>
    <family>Noto Color Emoji</family>
    <family>Noto Emoji</family>
   </prefer>
 </alias>
</fontconfig>```

Now it looks like this.

![rofi-2019-07-01-1106](https://user-images.githubusercontent.com/3732535/60457370-b5704180-9bf0-11e9-829f-8eec9850fc3c.png)
![rofi-2019-07-01-1107](https://user-images.githubusercontent.com/3732535/60457375-b903c880-9bf0-11e9-9e71-2c7931211046.png)

Here's a list of all the fonts on my system.

```/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf: DejaVu Serif:style=Bold
/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf: DejaVu Sans Mono:style=Book
/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Oblique.ttf: DejaVu Sans,DejaVu Sans Condensed:style=Condensed Oblique,Oblique
/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Italic.ttf: Liberation Sans Narrow:style=Italic
/usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed-BoldItalic.ttf: DejaVu Serif,DejaVu Serif Condensed:style=Condensed Bold Italic,Bold Italic
/usr/share/fonts/truetype/dejavu/DejaVuSans-ExtraLight.ttf: DejaVu Sans,DejaVu Sans Light:style=ExtraLight
/usr/share/fonts/type1/gsfonts/n021024l.pfb: Nimbus Roman No9 L:style=Medium Italic
/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf: DejaVu Sans:style=Book
/usr/share/fonts/type1/gsfonts/n021004l.pfb: Nimbus Roman No9 L:style=Medium
/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf: Liberation Sans:style=Regular
/usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed.ttf: DejaVu Serif,DejaVu Serif Condensed:style=Condensed,Book
/usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed-Italic.ttf: DejaVu Serif,DejaVu Serif Condensed:style=Condensed Italic,Italic
/usr/share/fonts/type1/gsfonts/p052023l.pfb: URW Palladio L:style=Italic
/usr/share/fonts/type1/gsfonts/n022003l.pfb: Nimbus Mono L:style=Regular
/usr/share/fonts/truetype/liberation/LiberationMono-BoldItalic.ttf: Liberation Mono:style=Bold Italic
/usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf: Liberation Serif:style=Italic
/usr/share/fonts/type1/gsfonts/z003034l.pfb: URW Chancery L:style=Medium Italic
/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf: Liberation Mono:style=Bold
/usr/share/fonts/type1/gsfonts/c059013l.pfb: Century Schoolbook L:style=Roman
/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Regular.ttf: Liberation Sans Narrow:style=Regular
/usr/share/fonts/opentype/mathjax/MathJax_Typewriter-Regular.otf: MathJax_Typewriter:style=Regular
/usr/share/fonts/truetype/vlgothic/VL-PGothic-Regular.ttf: VL PGothic,VL Pゴシック:style=regular
/usr/share/fonts/type1/gsfonts/d050000l.pfb: Dingbats:style=Regular
/usr/share/fonts/truetype/dejavu/DejaVuSerif-BoldItalic.ttf: DejaVu Serif:style=Bold Italic
/usr/share/fonts/opentype/mathjax/MathJax_Fraktur-Bold.otf: MathJax_Fraktur:style=Bold
/usr/share/fonts/type1/gsfonts/n021023l.pfb: Nimbus Roman No9 L:style=Regular Italic
/usr/share/fonts/type1/gsfonts/n019063l.pfb: Nimbus Sans L:style=Regular Condensed Italic
/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Oblique.ttf: DejaVu Sans Mono:style=Oblique
/usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed-Bold.ttf: DejaVu Serif,DejaVu Serif Condensed:style=Condensed Bold,Bold
/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf: DejaVu Sans:style=Bold
/usr/share/fonts/opentype/mathjax/MathJax_Math-Italic.otf: MathJax_Math:style=Italic
/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf: Liberation Serif:style=Bold
/usr/share/fonts/truetype/dejavu/DejaVuSansMono-BoldOblique.ttf: DejaVu Sans Mono:style=Bold Oblique
/usr/share/fonts/type1/gsfonts/a010013l.pfb: URW Gothic L:style=Book
/usr/share/fonts/opentype/mathjax/MathJax_Main-Regular.otf: MathJax_Main:style=Regular
/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf: Liberation Mono:style=Regular
/usr/share/fonts/opentype/mathjax/MathJax_Fraktur-Regular.otf: MathJax_Fraktur:style=Regular
/usr/share/fonts/opentype/mathjax/MathJax_Caligraphic-Bold.otf: MathJax_Caligraphic:style=Bold
/usr/share/fonts/truetype/fonts-japanese-gothic.ttf: VL Gothic,VL ゴシック:style=regular
/usr/share/fonts/opentype/mathjax/MathJax_Caligraphic-Regular.otf: MathJax_Caligraphic:style=Regular
/usr/share/fonts/type1/gsfonts/n019064l.pfb: Nimbus Sans L:style=Bold Condensed Italic
/usr/share/fonts/truetype/dejavu/DejaVuMathTeXGyre.ttf: DejaVu Math TeX Gyre:style=Regular
/usr/share/fonts/truetype/liberation/LiberationSans-Italic.ttf: Liberation Sans:style=Italic
/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-BoldOblique.ttf: DejaVu Sans,DejaVu Sans Condensed:style=Condensed Bold Oblique,Bold Oblique
/usr/share/fonts/truetype/droid/DroidSansFallbackFull.ttf: Droid Sans Fallback:style=Regular
/usr/share/fonts/type1/gsfonts/p052004l.pfb: URW Palladio L:style=Bold
/usr/share/fonts/truetype/liberation/LiberationSerif-BoldItalic.ttf: Liberation Serif:style=Bold Italic
/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed.ttf: DejaVu Sans,DejaVu Sans Condensed:style=Condensed,Book
/usr/share/fonts/opentype/mathjax/MathJax_SansSerif-Bold.otf: MathJax_SansSerif:style=Bold
/usr/share/fonts/type1/gsfonts/n022023l.pfb: Nimbus Mono L:style=Regular Oblique
/usr/share/fonts/type1/gsfonts/a010015l.pfb: URW Gothic L:style=Demi
/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Bold.ttf: DejaVu Sans,DejaVu Sans Condensed:style=Condensed Bold,Bold
/usr/share/fonts/truetype/liberation/LiberationSansNarrow-BoldItalic.ttf: Liberation Sans Narrow:style=Bold Italic
/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf: DejaVu Sans Mono:style=Bold
/usr/share/fonts/type1/gsfonts/n019043l.pfb: Nimbus Sans L:style=Regular Condensed
/usr/share/fonts/truetype/dejavu/DejaVuSans-Oblique.ttf: DejaVu Sans:style=Oblique
/usr/share/fonts/type1/gsfonts/n019044l.pfb: Nimbus Sans L:style=Bold Condensed
/usr/share/fonts/opentype/mathjax/MathJax_Size4-Regular.otf: MathJax_Size4:style=Regular
/usr/share/fonts/type1/gsfonts/a010033l.pfb: URW Gothic L:style=Book Oblique
/usr/share/fonts/opentype/mathjax/MathJax_Size2-Regular.otf: MathJax_Size2:style=Regular
/usr/share/fonts/opentype/mathjax/MathJax_Main-Italic.otf: MathJax_Main:style=Italic
/usr/share/fonts/type1/gsfonts/n021003l.pfb: Nimbus Roman No9 L:style=Regular
/usr/share/fonts/type1/gsfonts/s050000l.pfb: Standard Symbols L:style=Regular
/usr/share/fonts/truetype/vlgothic/VL-Gothic-Regular.ttf: VL Gothic,VL ゴシック:style=regular
/usr/share/fonts/opentype/mathjax/MathJax_Size3-Regular.otf: MathJax_Size3:style=Regular
/usr/share/fonts/opentype/mathjax/MathJax_Math-BoldItalic.otf: MathJax_Math:style=BoldItalic
/usr/share/fonts/opentype/mathjax/MathJax_AMS-Regular.otf: MathJax_AMS:style=Regular
/usr/share/fonts/truetype/liberation/LiberationMono-Italic.ttf: Liberation Mono:style=Italic
/usr/share/fonts/truetype/liberation/LiberationSans-BoldItalic.ttf: Liberation Sans:style=Bold Italic
/usr/share/fonts/type1/gsfonts/b018035l.pfb: URW Bookman L:style=Demi Bold Italic
/usr/share/fonts/type1/gsfonts/c059033l.pfb: Century Schoolbook L:style=Italic
/usr/share/fonts/opentype/mathjax/MathJax_Size1-Regular.otf: MathJax_Size1:style=Regular
/usr/share/fonts/type1/gsfonts/a010035l.pfb: URW Gothic L:style=Demi Oblique
/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf: Liberation Serif:style=Regular
/usr/share/fonts/truetype/dejavu/DejaVuSerif-Italic.ttf: DejaVu Serif:style=Italic
/usr/share/fonts/opentype/mathjax/MathJax_Math-Regular.otf: MathJax_Math:style=Regular
/home/kavus/.fonts/NotoEmoji-Regular.ttf: Noto Emoji:style=Regular
/usr/share/fonts/type1/gsfonts/n019023l.pfb: Nimbus Sans L:style=Regular Italic
/usr/share/fonts/type1/gsfonts/b018012l.pfb: URW Bookman L:style=Light
/usr/share/fonts/type1/gsfonts/c059016l.pfb: Century Schoolbook L:style=Bold
/usr/share/fonts/type1/gsfonts/n022004l.pfb: Nimbus Mono L:style=Bold
/usr/share/fonts/type1/gsfonts/n019024l.pfb: Nimbus Sans L:style=Bold Italic
/usr/share/fonts/type1/gsfonts/b018032l.pfb: URW Bookman L:style=Light Italic
/usr/share/fonts/type1/gsfonts/p052003l.pfb: URW Palladio L:style=Roman
/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Bold.ttf: Liberation Sans Narrow:style=Bold
/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf: Liberation Sans:style=Bold
/usr/share/fonts/opentype/mathjax/MathJax_WinIE6-Regular.otf: MathJax_WinIE6:style=Regular
/usr/share/fonts/type1/gsfonts/n019004l.pfb: Nimbus Sans L:style=Bold
/usr/share/fonts/type1/gsfonts/b018015l.pfb: URW Bookman L:style=Demi Bold
/usr/share/fonts/opentype/mathjax/MathJax_Script-Regular.otf: MathJax_Script:style=Regular
/usr/share/fonts/type1/gsfonts/n022024l.pfb: Nimbus Mono L:style=Bold Oblique
/usr/share/fonts/opentype/mathjax/MathJax_Main-Bold.otf: MathJax_Main:style=Bold
/usr/share/fonts/type1/gsfonts/c059036l.pfb: Century Schoolbook L:style=Bold Italic
/usr/share/fonts/type1/gsfonts/p052024l.pfb: URW Palladio L:style=Bold Italic
/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf: DejaVu Serif:style=Book
/usr/share/fonts/opentype/mathjax/MathJax_SansSerif-Italic.otf: MathJax_SansSerif:style=Italic
/usr/share/fonts/opentype/mathjax/MathJax_WinChrome-Regular.otf: MathJax_WinChrome:style=Regular
/usr/share/fonts/opentype/mathjax/MathJax_SansSerif-Regular.otf: MathJax_SansSerif:style=Regular
/usr/share/fonts/truetype/dejavu/DejaVuSans-BoldOblique.ttf: DejaVu Sans:style=Bold Oblique
/usr/share/fonts/type1/gsfonts/n019003l.pfb: Nimbus Sans L:style=Regular```

Wait... Noto Color Emoji isn't in this list. Have I been doing something wrong this whole time?

I have them in the right folder.

```kavus@micropc:~$ ls ~/.fonts/
Blobmoji.ttf  NotoColorEmoji.ttf  NotoEmoji-Regular.ttf```

**Comment by Silent-Hunter** [comment] 2019-07-01 18:50
Okay, I downloaded Twitter Color Emoji (formerly EmojiOne) and edited my fontconfig so only rofi and geany would use it, and everything else would use Blobmoji.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">

<fontconfig>
  <alias>
    <family>serif</family>
    <prefer>
      <family>Blobmoji</family>
    </prefer>
  </alias>
  <alias>
    <family>sans-serif</family>
    <prefer>
      <family>Blobmoji</family>
    </prefer>
  </alias>
  <alias>
    <family>monospace</family>
    <prefer>
      <family>Blobmoji</family>
    </prefer>
  </alias>

    <match target="pattern">
    <test name="prgname" qual="any">
      <string>rofi</string>
    </test>
    <edit name="family" mode="prepend_first">
      <string>Twitter Color Emoji</string>
    </edit>
  </match>

      <match target="pattern">
    <test name="prgname" qual="any">
      <string>geany</string>
    </test>
    <edit name="family" mode="prepend_first">
      <string>Twitter Color Emoji</string>
    </edit>
  </match>
</fontconfig>
```
rofimoji now looks like this.

![rofi-2019-07-01-1149](https://user-images.githubusercontent.com/3732535/60459541-54e40300-9bf6-11e9-9e49-c00bd4d961b5.png)
![rofi-2019-07-01-1149-1](https://user-images.githubusercontent.com/3732535/60459542-54e40300-9bf6-11e9-9e5f-e609f411a5c5.png)

Still no color, and ZWJ multipart emojis still don't look right, but there are no missing symbols now.

**Comment by fdw** [comment] 2019-07-01 19:50
Multipart emojis not working can be caused by the font not supporting the "ligature". Same with missing entries.

What I find interesting is that you seem to have only one emoji font, `Noto Emoji`. Is there some problem with the other fonts?
You can also call `fc-match 'Blobmoji'` to see which font is actually used.

Some more ideas: Do you set the text-color? What is your `rofi` version?

**Comment by Silent-Hunter** [comment] 2019-07-01 20:04
Okay, this is a possible issue and I'm not sure how to fix it.

```
kavus@micropc:~$ fc-match 'Blobmoji'
DejaVuSans.ttf: "DejaVu Sans" "Book"
```

My rofi is version 1.3.1, I installed it just to use rofimoji. I haven't changed anything in its config file at all yet.

**Comment by fdw** [comment] 2019-07-02 08:00
If they work in other browsers, then I definitely have no actual clue what happens 😉

One last hail mary: Have you run `fc-cache -fv`. Are the fonts listed with `fc-list`?

**Comment by Silent-Hunter** [comment] 2019-07-02 15:52
I've been running `fc-cache -f -v` every time I edit my fontconfig. It will say fonts were found in the .fonts folder, but when I run `fc-list` it won't show Blobmoji or Noto Color Emoji. It will show Twitter Color Emoji and Noto Emoji though.

I'm wondering if it's a problem with Cairo. Debian 10 comes out in a few days, maybe upgrading to that will fix the issue. The version of Cairo in Debian 9 is kind of old.

-------- Original Message --------

**Comment by fdw** [comment] 2019-07-02 16:14
Then all I can do is wish you good luck! Sorry rofimoji doesn't work ideally for you 😢

**Comment by Silent-Hunter** [comment] 2019-07-02 16:17
That's alright! It doesn't _look_ great, but it works fine and that's the more important bit. It's a great program.

**Comment by fdw** [comment] 2019-07-02 16:23
Thank you, that means a lot to me!

**Comment by fdw** [comment] 2019-07-27 09:52
As this seems to be a font issue and not something I can directly influence. I'll close this ticket. If something new comes up, feel free to re-open!

**Closed by fdw** 2019-07-27 09:52 UTC

**Comment by Silent-Hunter** [comment] 2019-07-27 20:46
Oh, I forgot to mention that updating to Debian 10 fixed it, so yes it's fine now.

**Comment by fdw** [comment] 2019-07-28 09:07
Perfect 🙂
