### ISSUE TITLE
Crash when clicking on a emoji to copy

### ISSUE THREAD

**Issue by matteodev8** [fdw/rofimoji#168] opened 2023-12-08 14:42 UTC
When trying to open Rofimoji and selecting an emoji (Using mouse click or enter), nothing happens and the window closes. When opening it via a CLI, it reports this Python error:

```
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/picker/__main__.py", line 11, in main
    ModeRofimoji().mode()
  File "/usr/lib/python3.11/site-packages/picker/mode.py", line 107, in mode
    self.execute_actions(state)
  File "/usr/lib/python3.11/site-packages/picker/mode.py", line 217, in execute_actions
    execute_action(state.processed_characters, state.actions)
  File "/usr/lib/python3.11/site-packages/picker/action.py", line 20, in execute_action
    typer.type_characters(characters, active_window)
  File "/usr/lib/python3.11/site-packages/picker/typer/typer.py", line 48, in type_characters
    run(["xdotool", "windowactivate", "--sync", active_window, "type", "--clearmodifiers", characters])
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1883, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

EndeavourOS (Arch Linux)
X11
Cinnamon 6.0.0
Rofi 1.7.5
Rofmoji 0.2.2 (AUR)
Python 3.11.6

**Comment by fdw** [comment] 2023-12-08 15:56
Do you use `rofimoji` standalone or as a rofi mode? Do you have `xdotool` installed? Any additional configuration?

**Comment by matteodev8** [comment] 2023-12-08 20:43
@fdw I am using `rofi -modi "emoji:rofimoji" -show emoji -a copy` to open it up. I installed xdtool and the other recommended tools and I haven't touched the config

**Comment by fdw** [comment] 2023-12-09 08:31
You need to pass `-a copy` to `rofimoji`, not to `rofi`. So it should be `rofi -modi "emoji:rofimoji -a copy" -show emoji`.

Does that help?

**Comment by fdw** [comment] 2024-01-06 17:59
Hey @matteodev8, could you try my suggestion? Do you still have problems with `rofimoji`?

**Comment by fdw** [comment] 2024-02-17 18:19
As it seems to have worked, I'll close this ticket. Feel free to re-open if the problem is still there.

**Closed by fdw** 2024-02-17 18:19 UTC

**Comment by AllenWu233** [comment] 2024-04-25 15:58
> You need to pass `-a copy` to `rofimoji`, not to `rofi`. So it should be `rofi -modi "emoji:rofimoji -a copy" -show emoji`.
> 
> Does that help?

Hi! I meet the same problem on Archlinux
I have run `rofi -modi "emoji:rofimoji -a type" -show emoji -dpi 1` and press ENTER to choose an emoji, then it reports:
```
usage: rofimoji [-h] [--version] [--action [ACTION ...]]
                [--skin-tone {neutral,light,medium-light,moderate,dark brown,black,ask}]
                [--files FILE [FILE ...]] [--prompt PROMPT]
                [--selector-args SELECTOR_ARGS] [--max-recent MAX_RECENT]
                [--no-frecency] [--only-official] [--hidden-descriptions]
                [--selector {rofi,wofi,fuzzel,dmenu}]
                [--clipboarder {xsel,xclip,wl-copy}] [--typer {xdotool,wtype}]
                [--keybinding-copy KEYBINDING_COPY]
                [--keybinding-type KEYBINDING_TYPE]
                [--keybinding-clipboard KEYBINDING_CLIPBOARD]
                [--keybinding-unicode KEYBINDING_UNICODE]
                [--keybinding-copy-unicode KEYBINDING_COPY_UNICODE]
rofimoji: error: argument --action/-a: invalid Action value: '😋 face savoring food <small>(delicious, face, face savoring food, savouring, smile, yum)</small>'
```

**Comment by AllenWu233** [comment] 2024-04-26 00:11
> Have you tried using a config file? Does it work if you set the action there?

After I creating `~/.config/rofimoji.rc` and add `action = type`

> Have you tried using a config file? Does it work if you set the action there?

Both running `rofi -modi "emoji:rofimoji" -show emoji -dpi 1` without config file
and running it with a config file(action = type) have the same report:
```
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/picker/__main__.py", line 11, in main
    ModeRofimoji().mode()
  File "/usr/lib/python3.11/site-packages/picker/mode.py", line 107, in mode
    self.execute_actions(state)
  File "/usr/lib/python3.11/site-packages/picker/mode.py", line 217, in execute_actions
    execute_action(state.processed_characters, state.actions)
  File "/usr/lib/python3.11/site-packages/picker/action.py", line 20, in execute_action
    typer.type_characters(characters, active_window)
  File "/usr/lib/python3.11/site-packages/picker/typer/typer.py", line 48, in type_characters
    run(["xdotool", "windowactivate", "--sync", active_window, "type", "--clearmodifiers", characters])
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1883, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
However, it works well when I set `action = copy` in the config file and run `rofi -modi "emoji:rofimoji" -show emoji -dpi 1`

**Comment by fdw** [comment] 2024-04-26 17:10
I'm sorry, I forgot that directly typing is not possible in the `rofi` mode, as described [in the readme](https://github.com/fdw/rofimoji?tab=readme-ov-file#caveats-when-running-rofimoji-as-a-rofi-mode). Sorry about that!

**Comment by AllenWu233** [comment] 2024-04-27 01:05
> I'm sorry, I forgot that directly typing is not possible in the `rofi` mode, as described [in the readme](https://github.com/fdw/rofimoji?tab=readme-ov-file#caveats-when-running-rofimoji-as-a-rofi-mode). Sorry about that!

Oh, thanks for your explanation!
