### ISSUE TITLE
TypeError: unsupported operand types; Prevents rofimoji from running

### ISSUE THREAD

**Issue by 12buntu** [fdw/rofimoji#141] opened 2022-12-11 13:34 UTC
When trying to run rofimoji, I get the following error:

```python
Traceback (most recent call last):
  File "/home/kyle/.local/bin/rofimoji", line 5, in <module>
    from picker.__main__ import main
  File "/home/kyle/.local/lib/python3.8/site-packages/picker/__main__.py", line 4, in <module>
    from .standalone import StandaloneRofimoji
  File "/home/kyle/.local/lib/python3.8/site-packages/picker/standalone.py", line 12, in <module>
    from .selector.selector import Selector
  File "/home/kyle/.local/lib/python3.8/site-packages/picker/selector/selector.py", line 9, in <module>
    class Selector:
  File "/home/kyle/.local/lib/python3.8/site-packages/picker/selector/selector.py", line 35, in Selector
    ) -> Tuple[Action | DEFAULT | CANCEL, List[str] | Shortcut]:
TypeError: unsupported operand type(s) for |: 'EnumMeta' and 'type'
```

I don't really know enough about Python to effectively debug this issue myself. I'm using Python 3.8.10 on elementaryOS, and have tried this both with the program downloaded from PyPI and the wheel file in Releases.

**Comment by fdw** [comment] 2022-12-11 14:52
I think this is a duplicate of #137, so it should already be fixed. I just haven't built a new release yet.

Can you maybe try `main`?

**Comment by 12buntu** [comment] 2022-12-11 15:24
Now I'm getting the output:
```
Traceback (most recent call last):
  File "/home/kyle/.local/bin/rofimoji", line 8, in <module>
    sys.exit(main())
  File "/home/kyle/.local/lib/python3.8/site-packages/picker/__main__.py", line 9, in main
    StandaloneRofimoji().standalone()
  File "/home/kyle/.local/lib/python3.8/site-packages/picker/standalone.py", line 22, in __init__
    self.active_window = self.typer.get_active_window()
  File "/home/kyle/.local/lib/python3.8/site-packages/picker/typer/typer.py", line 26, in get_active_window
    raise NoTyperFoundException()
picker.typer.typer.NoTyperFoundException: Could not find a valid way to type characters. Please check the required dependencies.
```

It's entirely possible that I just built it wrong. I've never used poetry before so I just ran:
```
$ poetry install
$ poetry build
$ cd dist && pip install rofimoji-6.1.0.dev1-py3-none-any.whl --force-reinstall
```

**Comment by fdw** [comment] 2022-12-11 15:39
That looks correct. Do you have `xdotool` or `wtype` installed?

**Comment by artebin** [comment] 2022-12-25 11:12
Same problem here with a freshly installed Debian 11, pip install without and with the wheel file:

```
Traceback (most recent call last):
  File "/home/njames/.local/bin/rofimoji", line 5, in <module>
    from picker.__main__ import main
  File "/home/njames/.local/lib/python3.9/site-packages/picker/__main__.py", line 4, in <module>
    from .standalone import StandaloneRofimoji
  File "/home/njames/.local/lib/python3.9/site-packages/picker/standalone.py", line 12, in <module>
    from .selector.selector import Selector
  File "/home/njames/.local/lib/python3.9/site-packages/picker/selector/selector.py", line 9, in <module>
    class Selector:
  File "/home/njames/.local/lib/python3.9/site-packages/picker/selector/selector.py", line 35, in Selector
    ) -> Tuple[Action | DEFAULT | CANCEL, List[str] | Shortcut]:
TypeError: unsupported operand type(s) for |: 'EnumMeta' and 'type'
```

**Comment by fdw** [comment] 2022-12-25 12:20
As I said before: This is fixed on `main`, but there hasn't been a release since then. The wheel file is expected to be broken at the moment, sorry.

Maybe I'll build a release in the next weeks.

**Comment by fdw** [comment] 2022-12-27 09:08
Since the release is now out, I'll close this bug. If anything new happens, please open a new one! 🙂

**Closed by fdw** 2022-12-27 09:08 UTC
